// 性格标签多语言映射
// key 为标准英文标识，value 为各语言翻译

export const personalityTagTranslations: Record<string, Record<string, string>> = {
  zh: {
    gentle: "温柔",
    cute: "可爱",
    mature: "成熟",
    scheming: "腹黑",
    lively: "活泼",
    sunny: "阳光",
    quiet: "安静",
    straightforward: "直率",
    warm: "温暖",
    calm: "冷静",
    cool: "酷",
    artsy: "文艺",
    "fun-loving": "爱玩",
    relaxed: "放松",
    outgoing: "外向",
    passionate: "热情",
    elegant: "优雅",
    creative: "有创意",
    intense: "热烈",
    polite: "有礼貌",
    "easy-going": "随和",
  },
  en: {
    gentle: "gentle",
    cute: "cute",
    mature: "mature",
    scheming: "scheming",
    lively: "lively",
    sunny: "sunny",
    quiet: "quiet",
    straightforward: "straightforward",
    warm: "warm",
    calm: "calm",
    cool: "cool",
    artsy: "artsy",
    "fun-loving": "fun-loving",
    relaxed: "relaxed",
    outgoing: "outgoing",
    passionate: "passionate",
    elegant: "elegant",
    creative: "creative",
    intense: "intense",
    polite: "polite",
    "easy-going": "easy-going",
  },
  ja: {
    gentle: "優しい",
    cute: "かわいい",
    mature: "成熟した",
    scheming: "腹黒い",
    lively: "活発",
    sunny: "明るい",
    quiet: "静か",
    straightforward: "率直",
    warm: "温かい",
    calm: "冷静",
    cool: "クール",
    artsy: "アーティスティック",
    "fun-loving": "楽しいのが好き",
    relaxed: "リラックス",
    outgoing: "外向的",
    passionate: "情熱的",
    elegant: "優雅",
    creative: "創造的",
    intense: "激しい",
    polite: "丁寧",
    "easy-going": "気さく",
  },
  ko: {
    gentle: "다정한",
    cute: "귀여운",
    mature: "성숙한",
    scheming: "속이 검은",
    lively: "활발한",
    sunny: "밝은",
    quiet: "조용한",
    straightforward: "솔직한",
    warm: "따뜻한",
    calm: "침착한",
    cool: "쿨한",
    artsy: "예술적인",
    "fun-loving": "즐거움을 사랑하는",
    relaxed: "여유로운",
    outgoing: "외향적인",
    passionate: "열정적인",
    elegant: "우아한",
    creative: "창의적인",
    intense: "강렬한",
    polite: "예의바른",
    "easy-going": "느긋한",
  },
  pt: {
    gentle: "gentil",
    cute: "fofo",
    mature: "maduro",
    scheming: "calculista",
    lively: "animado",
    sunny: "ensolarado",
    quiet: "quieto",
    straightforward: "direto",
    warm: "caloroso",
    calm: "calmo",
    cool: "legal",
    artsy: "artístico",
    "fun-loving": "divertido",
    relaxed: "relaxado",
    outgoing: "extrovertido",
    passionate: "apaixonado",
    elegant: "elegante",
    creative: "criativo",
    intense: "intenso",
    polite: "educado",
    "easy-going": "descontraído",
  },
  es: {
    gentle: "gentil",
    cute: "lindo",
    mature: "maduro",
    scheming: "calculador",
    lively: "animado",
    sunny: "soleado",
    quiet: "tranquilo",
    straightforward: "directo",
    warm: "cálido",
    calm: "calmado",
    cool: "genial",
    artsy: "artístico",
    "fun-loving": "divertido",
    relaxed: "relajado",
    outgoing: "extrovertido",
    passionate: "apasionado",
    elegant: "elegante",
    creative: "creativo",
    intense: "intenso",
    polite: "educado",
    "easy-going": "despreocupado",
  },
  id: {
    gentle: "lembut",
    cute: "lucu",
    mature: "dewasa",
    scheming: "licik",
    lively: "lincah",
    sunny: "ceria",
    quiet: "tenang",
    straightforward: "blak-blakan",
    warm: "hangat",
    calm: "tenang",
    cool: "keren",
    artsy: "artistik",
    "fun-loving": "suka bersenang-senang",
    relaxed: "santai",
    outgoing: "ekstrovert",
    passionate: "penuh gairah",
    elegant: "anggun",
    creative: "kreatif",
    intense: "intens",
    polite: "sopan",
    "easy-going": "santai",
  },
};

// 反向映射：从任意语言标签值查找标准 key
const reverseMap: Record<string, string> = {};
Object.values(personalityTagTranslations).forEach((langMap) => {
  Object.entries(langMap).forEach(([key, value]) => {
    reverseMap[value.toLowerCase()] = key;
  });
});

export function translatePersonalityTag(tag: string, lang: string): string {
  const normalized = tag.trim().toLowerCase();
  const key = reverseMap[normalized];
  if (!key) return tag.trim();
  return personalityTagTranslations[lang]?.[key] || tag.trim();
}
